site_name: MovieDataset
nav:
    - Home: index.md
    - RDlite: rdlite.md
    - MovieClean: movieClean.md
    - dashProject: dashpro.md
    - Normalization: normalization.md

theme: readthedocs

plugins:
- mkdocstrings:
    handlers:
        python:
            paths: [.., ../MovieClean, ../RDlite, ../dashProject]
            rendering:
                show_source: false
                show_root_heading: false
                show_root_full_path: false

watch:
    - ../RDlite
    - ../MovieClean/MovieClean
    - ../dashProject